{% set version = "0.8.0.4" %}
{% set soversion = ".".join(version.split(".")[:4]) %}
{% set somajor = version.split(".")[0] %}
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "placeholder" %}  # [osx]
{% set extension = "tar.xz" %}  # [unix]
{% set platform = "windows-x86_64" %}  # [win64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: cusparselt-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/{{ platform }}/libcusparse_lt-{{ platform }}-{{ version }}_cuda12-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("12")]
  url: https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/{{ platform }}/libcusparse_lt-{{ platform }}-{{ version }}_cuda13-archive.{{ extension }}  # [(cuda_compiler_version or "").startswith("13")]
  sha256: b59e2f8ffd154b156b2d74ccd7cad7775385693bec8cb9562596060072c515f2  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
  sha256: 483954591766bade877becef126d53908d5fef5d7468b503736af37388669c08  # [linux64 and (cuda_compiler_version or "").startswith("12")]
  sha256: d2010d798336eb2df63bf54c5379e8f2f83f72fa21b4f1bf5c1168b541ae9599  # [win and (cuda_compiler_version or "").startswith("12")]
  sha256: 0a70952a00139e8cc60db282a041f4003febf1529f467ee997dc80770dd1faa1  # [linux64 and (cuda_compiler_version or "").startswith("13")]
  sha256: 849824258db33d850fb68be7d65e7e98375e98dfcbbda93275d124a0ea590dfe  # [aarch64 and (cuda_compiler_version or "").startswith("13")]
  sha256: 0fa0f02d95b3b00e7c48315d59452d71dffdc8e07a50936faf02cb5b7179c1ca  # [win and (cuda_compiler_version or "").startswith("13")]

build:
  number: 0
  skip: true  # [ppc64le or not (cuda_compiler_version or "").startswith(("12", "13"))]
  script:   # [win]
    - xcopy include %LIBRARY_INC% /E /I /Y /V  # [win]
    - copy lib\cusparseLt.lib %LIBRARY_LIB%\cusparseLt.lib /Y /V  # [win]
    - copy bin\cusparseLt.dll %LIBRARY_BIN%\cusparseLt.dll /Y /V  # [win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cuda') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - cf-nvidia-tools 1   # [linux]

outputs:

  - name: cusparselt
    build:
      ignore_run_exports:
        - cuda-version
    files:
      - lib/libcusparseLt.so.*              # [linux]
      - Library/bin/cusparseLt.dll          # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cuda') }}
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
      run:
        - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}  # [cuda_compiler_version != "None"]
    test:
      commands:
        - test -f $PREFIX/lib/libcusparseLt.so.{{ soversion }}  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so.{{ somajor }}  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - if not exist %LIBRARY_BIN%\\cusparseLt.dll exit 1  # [win]
    about:
      summary: The NVIDIA cuSPARSELt runtime library
      license: LicenseRef-cuSPARSELt-Software-License-Agreement
      license_file: LICENSE
      description: >-
        This is a runtime package only. Developers should install cusparselt-dev to build with cuSPARSELt.

  - name: cusparselt-dev
    build:
      run_exports:
        # Breaking changes every version until 1.0
        - {{ pin_subpackage("cusparselt", max_pin="x.x.x") }}
    files:
      - lib/libcusparseLt.so    # [linux]
      - include/cusparseLt.h    # [linux]
      - Library/lib/cusparseLt.lib    # [win]
      - Library/include/cusparseLt.h  # [win]
    requirements:
      host:
        - {{ pin_subpackage("cusparselt", exact=True) }}
      run:
        - {{ pin_subpackage("cusparselt", exact=True) }}
    test:
      files:
        - test/test_load_elf.c        # [linux]
        - test/run_test.sh   # [linux]
        - test/run_test.bat  # [win]
      commands:
        - test -f $PREFIX/include/cusparseLt.h  # [linux]
        - test -L $PREFIX/lib/libcusparseLt.so  # [linux]
        - test ! -f $PREFIX/lib/libcusparseLt_static.a  # [linux]
        - bash test/run_test.sh  # [linux]
        - if not exist %LIBRARY_LIB%\\cusparseLt.lib exit 1  # [win]
        - if not exist %LIBRARY_INC%\\cusparseLt.h exit 1  # [win]
        - test/run_test.bat  # [win]
      requires:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
        - cmake
        - ninja
        - git
        - libcusparse-dev # test_load_elf needs the cuSPARSE header & libnvrtc.s
        - cuda-nvrtc-dev
        - cuda-driver-dev

about:
  home: https://developer.nvidia.com/cusparse
  license: LicenseRef-cuSPARSELt-Software-License-Agreement
  license_url: https://docs.nvidia.com/cuda/cusparselt/license.html
  license_file: LICENSE
  summary: "Basic Linear Algebra for Sparse Matrices on NVIDIA GPUs"
  description: |
    NVIDIA cuSPARSELt is a high-performance CUDA library dedicated to general
    matrix-matrix operations in which at least one operand is a structured sparse matrix
    with 50\% sparsity.
    The cuSPARSELt APIs allow flexibility in the algorithm/operation selection,
    epilogue, and matrix characteristics, including memory layout,
    alignment, and data types.
    License Agreements:- The packages are governed by the NVIDIA cuSPARSELt
    Software License Agreement (EULA). By downloading and using the packages,
    you accept the terms and conditions of the NVIDIA cuSPARSELt EULA -
    https://docs.nvidia.com/cuda/cusparselt/license.html
  doc_url: https://docs.nvidia.com/cuda/cusparselt/index.html
  dev_url: https://developer.nvidia.com/cusparselt/downloads

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - kvoronin
    - mtjrider
    - mnicely
    - leofang
